DOCUMENTATION: https://annoying-api.srnyx.com/wiki/file-objects


recipe:
  ingredients:
    A: APPLE
    D: DIAMOND
  shapeless: true
  shape:
    - " D "
    - "DAD"
    - " D "
  result:
    material: DIAMOND_PICKAXE
    count: 1
    damage: 561
    name: "&c&lGOD PICKAXE"
    lore:
      - "&7The most epic pickaxe in the game!"
      - "&7&oMake sure not to drop it..."
    enchantments:
      DIG_SPEED: 5
      LOOT_BONUS_MOBS: 2
    flags:
      - HIDE_ENCHANTS
    unbreakable: false
    attribute-modifiers:
      GENERIC_ATTACK_DAMAGE:
        name: attack_boost
        operation: ADD_NUMBER
        amount: 20
      GENERIC_MAX_HEALTH:
        name: health_boost
        operation: ADD_SCALAR
        amount: 5
    custom-model-data: 4508
    data:
      config: true

sound:
  sound: ENTITY_GENERIC_EXPLODE
  category: BLOCKS
  volume: 0.5
  pitch: 1.5
