name: ${name}
description: Plugin to test/give an example use of AnnoyingAPI
authors:
  - srnyx
website: https://srnyx.com

main: xyz.srnyx.annoyingexample.ExamplePlugin
version: ${version}

commands:
  test:
    description: Test command
    aliases:
      - t

permissions:
  test.command:
    description: Permission to use test command
    default: true
